using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

//ì¬Ò:™R
//”g‚ÉG‚Á‚Ä‚¢‚é‚©”»’f
public class JudgeTouchWave : MonoBehaviour
{
    public event Action<bool> SwitchTouchNowAction;//”g‚ÌÚGó‘Ô‚ªØ‚è‘Ö‚í‚Á‚½‚ÉŒÄ‚Ô(true‚¾‚ÆG‚ê‚½Afalse‚¾‚Æ—£‚ê‚½)
    public event Action TouchAction;//”g‚ÉG‚ê‚½uŠÔ‚ÉŒÄ‚Ô
    public event Action LeaveAction;//”g‚©‚ç—£‚ê‚½uŠÔ‚ÉŒÄ‚Ô
    [SerializeField] OnTriggerActionEvent onTriggerActionEvent;
    [SerializeField] float touchBorderTime = 0.1f;//G‚Á‚½EG‚Á‚Ä‚È‚¢‚Ì‹«ŠE‚ÌŠÔ
    private bool touchWaveNow=false;//¡”g‚ÉG‚Á‚Ä‚¢‚é‚©
    private float sinceLastTouchWaveTime = 0.1f;//ÅŒã‚É”g‚ÉG‚Á‚Ä‚©‚ç‚ÌŠÔ
   
    public bool TouchWaveNow
    {
        get { return touchWaveNow; }
    }

    void Start()
    {
        onTriggerActionEvent.EnterAction += TouchWave;
        sinceLastTouchWaveTime = touchBorderTime;
    }

    void Update()
    {
        JudgeTouchWaveNow();//”g‚ÉG‚ê‚Ä‚¢‚é‚©”»’è
    }

    public void TouchWave(Collider c)
    {
        if (c.gameObject.CompareTag("InsideWave") || c.gameObject.CompareTag("OutsideWave"))
        {
            sinceLastTouchWaveTime = 0f;//ÅŒã‚É”g‚ÉG‚Á‚Ä‚©‚ç‚ÌŠÔ‚ğXV
            touchWaveNow = true;
            //“o˜^‚µ‚½ˆ—‚ğŒÄ‚Ô
            TouchAction?.Invoke();
            SwitchTouchNowAction?.Invoke(true);
        }
    }

    void JudgeTouchWaveNow()//”g‚ÉG‚ê‚Ä‚¢‚é‚©”»’è
    {
        if (!touchWaveNow) return;

        sinceLastTouchWaveTime += Time.deltaTime;

        //ÅŒã‚É”g‚ÉG‚ê‚Ä‚©‚çtouchBorderTime•bˆÈãŒo‚Á‚½‚ç”g‚©‚ç—£‚ê‚½”»’è‚Æ‚·‚é
        if(sinceLastTouchWaveTime >= touchBorderTime)
        {
            touchWaveNow = false;
            //“o˜^‚µ‚½ˆ—‚ğŒÄ‚Ô
            LeaveAction?.Invoke();
            SwitchTouchNowAction?.Invoke(false);
        }
    }
}
