using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TouchWave : MonoBehaviour
{
    [HideInInspector] public bool touchWaveNow=false;//¡”g‚ÉG‚Á‚Ä‚¢‚é‚©
    private float sinceLastTouchWaveTime = 0.1f;//ÅŒã‚É”g‚ÉG‚Á‚Ä‚©‚ç‚ÌŠÔ
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        JudgeTouchWave();////”g‚ÉG‚ê‚Ä‚¢‚é‚©”»’è
    }

    void OnTriggerEnter(Collider t)
    {
        if (t.gameObject.CompareTag("InsideWave") || t.gameObject.CompareTag("OutsideWave"))//”g‚ÉG‚ê‚Ä‚¢‚é‚È‚çWave‚Ìî•ñ(isTouched)‚ğæ“¾
        {
            sinceLastTouchWaveTime = 0f;//ÅŒã‚É”g‚ÉG‚Á‚Ä‚©‚ç‚ÌŠÔ
        }
    }

    void JudgeTouchWave()//”g‚ÉG‚ê‚Ä‚¢‚é‚©”»’è
    {
        sinceLastTouchWaveTime += Time.deltaTime;

        if (sinceLastTouchWaveTime < 0.1f)
        {
            touchWaveNow = true;
        }
        else
        {
            touchWaveNow = false;
        }
    }
}
