using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AttackTimingOfEnemy : MonoBehaviour
{
    [SerializeField] GameObject enemy;//“G
    [SerializeField] float firstBeginAttackingTime = 5f;//“G‚ªŸ‚ÉUŒ‚‚ğn‚ß‚éŠÔ(‰‰ñ)
    [SerializeField] float minBeginAttackingTime = 0.1f;//“G‚ªŸ‚ÉUŒ‚‚ğn‚ß‚éÅ¬ŠÔ
    [SerializeField] float maxBeginAttackingTime = 0.4f;//“G‚ªŸ‚ÉUŒ‚‚ğn‚ß‚éÅ‘åŠÔ
    private float beginAttackingTime;//“G‚ªŸ‚ÉUŒ‚‚ğn‚ß‚éŠÔ
    private float attackTime = 0f;//“G‚ÌUŒ‚‚ğŠÇ—‚·‚éŠÔ
    AttackPatternOfEnemy attackPatternOfEnemy;
   
    
    // Start is called before the first frame update
    void Start()
    {
        attackPatternOfEnemy = enemy.GetComponent<AttackPatternOfEnemy>();
        beginAttackingTime = firstBeginAttackingTime;
    }

    // Update is called once per frame
    void Update()
    {
        AttackTiming();
    }

    void AttackTiming()//“G‚ÌUŒ‚ƒ^ƒCƒ~ƒ“ƒO
    {
        attackTime += Time.deltaTime;

        if(attackTime>beginAttackingTime)
        {
            attackTime = 0f;
            beginAttackingTime = Random.Range(minBeginAttackingTime,maxBeginAttackingTime);
            attackPatternOfEnemy.Attack();
        }
    }

    
}
